### PR TITLE
feat: add the plugin CLI to the package

### PR DESCRIPTION
**Pull request by rholshausen**
Downloads the plugin CLI binary and unpacks it into the bin directory during packaging

### CODE REVIEW

**Comment by bethesque** [comment]
I think the rake way of getting files it to wrap it in a task like this:

```
file "build/traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86_64.tar.gz" do
  download_runtime(TRAVELING_RUBY_VERSION, "linux-x86_64")
end
```

and then add it as a dependency for the task:

```
task :x86_64 => [:bundle_install, "build/traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86_64.tar.gz"] do
      create_package(TRAVELING_RUBY_VERSION, "linux-x86_64", "linux-x86_64", :unix)
    end
```

Then it only executes if you don't already have it downloaded.

**Comment by rholshausen** [comment]
I think it is better to always download the file, as it is being built on CI we want to ensure the correct version is in the bundle and not a previous version. It will probably always have to download it anyway.

**Comment by bethesque** [comment]
Righto.

**Comment by YOU54F** [comment]
Should we distribute this with the pact-ruby-standalone?

If I am using a ruby backed core language, I now have a fatter bundle, just to use the pact-mock_service.

I wonder if we should actually just have cross platform scripts that can download the relevant cli tool, and install for your environment.

Everything could be installed in the users home `~/home/.pact/` folder

```
- ffi 
  - version
    - arch
  - headers
- standalone
- cli
  - verifier
  - plugin
  - etc
```

That way languages wouldn't need to deal with packaging and distributing the binaries, and we could just assume a named place where they may be and the user can override if they live somewhere ever.

There is at least 3 different ways to install the FFI and CLI tools

Screenshot 2022-11-23 at 20 03 17

**Comment by rholshausen** [comment]
> Ah, this won't automatically update the commands available to the docker version of this will it https://hub.docker.com/r/pactfoundation/pact-cli?

No, this just adds it into the bundle in the bin directory, so it should end up in the docker image. But we still need to update the entry CLI to know about it.

But maybe we should have a discussion (as per @YOU54F comments) about if this is the right way to go.

**Comment by bethesque** [comment]
> No, this just adds it into the bundle in the bin directory, so it should end up in the docker image. But we still need to update the entry CLI to know about it.

The docker image is created separately. The pact-ruby-standalone does not go into the pact-cli image.

**Comment by bethesque** [comment]
It's definitely worth weighing up the pros and cons of each approach to work out which way is best for this situation and the users.

**Comment by mefellows** [comment]
(crap, never hit enter here)

The Pact Ruby Standalone is used in the Ruby apps, yes, but it also one of the two (or perhaps 3) main ways we tell people to get the [CLI](https://docs.pact.io/implementation_guides/cli#distributions). Not all will use Docker, and this package provides a cross platform way to get the key CLI tools.

I do like the idea of separating the two main concerns we have:

1. A shared core for the ruby-based languages
2. A simple way to get all of the important CLI commands

My suggestion is that we start by bundling it in here, because I'm not sure we have a straightforward path to your (wonderful) suggestions.

There are some complications in your suggestion that we would need to work through. For example, installing the FFI in the home directory won't work for Golang because of the esoteric way it actually uses it (it needs linking commands to be baked into the code, which can't used dynamic variables like $HOME). 

Perhaps we could use some metrics to see how often the bundle is downloaded (that doesn't involve the Pact JS and other language bundling)? I'm not sure we can get that in a straightforward way?

Oh and also, having the plugin CLI in the bundle will help those languages too - because now the plugin CLI can be relied upon to exist for any projects using plugins :)

**Comment by mefellows** [comment]
How do we want to proceed folks?

**Comment by bethesque** [comment]
I think we just put it in the standalone for now.

**Review by YOU54F — APPROVED** [review]

**Comment by YOU54F** [comment]
>My suggestion is that we start by bundling it in here, because I'm not sure we have a straightforward path to your (wonderful) suggestions.

Agreed, it helps us move forward, bring the plugin cli to the fingertips of more people, and we can broach the subject in a wider setting and get feedback on a configuration setup that works well for users.

**Pull request merged**
