### PR TITLE
docs: update install and usage step

### PR DESCRIPTION
**Pull request by edouard-lopez**
Leverage `install.sh` script

### CODE REVIEW

**Comment by bethesque** [comment]
Thank you! 

Every release used to actually have this documentation, but it seems to have disappeared. Would you be up for have a look at why it's gone and fixing it?

Screen Shot 2023-01-20 at 10 52 22 am

**Comment by bethesque** [comment]
A bunch of the help commands have disappeared too.

Some breadcrumbs for fixing this:

This is the last release I can find that had the release notes with installation instructions - something went wrong after this https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.22.1

https://github.com/pact-foundation/pact-ruby-standalone/blob/master/script/prepare-release-in-github-workflow.sh#L20
https://github.com/pact-foundation/pact-ruby-standalone/blob/060f172ac16746f176a3b29e9660c10216d429e1/tasks/release.rake#L13

**Comment by edouard-lopez** [comment]
That's what your https://github.com/pact-foundation/pact-ruby-standalone/blob/158cf7d7fb07bc17d5b11ead4307c561bfce41ff/install.sh script is doing I reckon.

**Comment by YOU54F** [comment]
> A bunch of the help commands have disappeared too.
> 
> Some breadcrumbs for fixing this:
> 
> This is the last release I can find that had the release notes with installation instructions - something went wrong after this https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.22.1
> 
> https://github.com/pact-foundation/pact-ruby-standalone/blob/master/script/prepare-release-in-github-workflow.sh#L20
> 
> https://github.com/pact-foundation/pact-ruby-standalone/blob/060f172ac16746f176a3b29e9660c10216d429e1/tasks/release.rake#L13

The install commands are there but you get a truncated view on the releases page

Screenshot 2023-05-11 at 10 03 27
Screenshot 2023-05-11 at 10 03 42

If you click through on the version number, it takes you to the tag

https://github.com/pact-foundation/pact-ruby-standalone/releases/tag/v1.92.0

which shows the full release notes, so I think the issue is I believe GitHub truncates the view of the readme/release note content, shown on the releases page.


Screenshot 2023-05-11 at 10 06 19



I think the README.md should when generated, and committed back to the repo

**Comment by YOU54F** [comment]
I'll merge this now so you get attribution but will rework the readme and templates in an upcoming pr, danke.

**Pull request merged**
