### PR TITLE
fix(rack-test): Update rack-test version to fix pact-ruby issue 198

### PR DESCRIPTION
**Pull request by TimothyJones**
I *think* this fixes the issue we're experiencing with DELETE requests in pact-node (https://github.com/pact-foundation/pact-node/issues/183), which is also reported here: https://github.com/pact-foundation/pact-ruby/issues/198

But my Ruby-fu is not strong, so I'm not certain.

### CODE REVIEW

**Comment by bethesque** [comment]
There were a couple of breaking changes in the move to 1.0 that someone else was going to investigate for me, but they never got back to me. I'll see if I can find the issue.

**Comment by bethesque** [comment]
Ok, I did allow 1.0+, and it seems it hasn't broken anything that anyone has noticed. https://github.com/pact-foundation/pact-ruby/pull/181

**Comment by bethesque** [comment]
We may be able to remove the dependency definition from this location altogether because it's already specified in one of the other gems. UNLESS rack-test 1.1 doesn't work on ruby 2.2 (I think the latest version of Rack itself doesn't).

**Comment by TimothyJones** [comment]
Any option sounds fine to me (I only just learnt how Gemfiles work).

I'm just looking for the fix for the http DELETE behaviour (fixed in rack test 1.1), so that we can get it in pact-node :)

**Comment by bethesque** [comment]
Done it on master.

**Comment by bethesque** [comment]
Upgrade to 1.73.0 at will.

**Pull request closed without merging**
